/* App.svelte generated by Svelte v3.52.0 */
import { create_ssr_component } from "svelte/internal";
import { parse } from 'node-html-parser';


export function atHTMLServer(htmltag: string) {

    const App = create_ssr_component(($$result:any, $$props:any, $$bindings:any, slots:any) => {
        const doc = parse(htmltag);
        const _slots = doc.getElementsByTagName("slot");
        const getName = (v:any)=>v.attributes?.name||"default";
        _slots.forEach(v=>{
            if (getName(v) in slots){
                const string = slots[getName(v)]();
                v.replaceWith(`~~at-html~~~ASTART~~at-html~~~B` +
                    string +
                    `~~at-html~~~C`)
            }else{
                v.replaceWith(v.innerHTML);
            }
        })
        const res = doc.toString()
            .replaceAll("~~at-html~~~A","<!-- HTML_SLOT_")
            .replaceAll("~~at-html~~~B"," -->")
            .replaceAll("~~at-html~~~C","<!-- HTML_SLOT_END -->")
        
        return `<!-- HTML_TAG_START -->${res}<!-- HTML_TAG_END -->`;
    });

    return App
}